### ISSUE TITLE
两点小建议

### ISSUE THREAD

**Issue by renyijiu** [otakurice/notravellist#1]
偶然在微博看到的文章，挺有意思的，有两点小建议

1.  去哪儿网页中自定义属性可以取到坐标点，就不需要调取百度地图API了
2.  可以直接使用.json后缀访问，能够取到json数据，不需要解析网页了

**Comment by otakurice** [comment]
第一个问题已经更新了，第二个问题QAQ恕我直言没看懂

**Comment by renyijiu** [comment]
现在看代码用的是 *http://piao.qunar.com/ticket/list.htm* 地址，换成
 *http://piao.qunar.com/ticket/list.json* 看看，你要的数据都有 @otakurice

**Comment by otakurice** [comment]
@renyijiu 哇 又学到了 谢谢！~
